spring:
  profiles:
    active: master
  application:
    name: spring_cloud_eureka


---
spring:
  profiles: master
server:
  port: 8761

eureka:
  instance:
    hostname: master
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://slave:8761/eureka/
  server:
    enable-self-preservation: false

---
spring:
  profiles: slave
server:
  port: 8762
eureka:
  instance:
    hostname: slave
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://master:8761/eureka/
  server:
    enable-self-preservation: false

